# Generated by Django 3.1.4 on 2021-01-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210107_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date_time',
            new_name='due_date',
        ),
    ]
